### ISSUE TITLE
大佬，没懂这个工具干嘛的？

### ISSUE THREAD

**Issue by 3538532** [secret2base/AttendanceStatisticsAssistant#3]
能解释一下不？

另外，能不能来个得力e+自动打卡？

**Comment by secret2base** [comment]
由于得力e+APP仅显示打卡时间，时长统计功能需要管理员权限才可查看，因此编写这个工具用于自动计算当前日所在周每天的在岗时间，并统计当前周的所有在岗时间之和，免去手工计算之苦。仅根据我所在的实验室规章制度统计，因此在其他情况下可能未具备泛用性。至于自动打卡，和此工具的设计目标不一致，且个人技术目前做不到。
