### ISSUE TITLE
运行出错。。。

### ISSUE THREAD

**Issue by drw2005** [secret2base/AttendanceStatisticsAssistant#4]
提示如图，是啥原因？

![QQ截图20230324081933](https://user-images.githubusercontent.com/33473981/227392663-c41427ea-7f3d-4582-8d1b-4b51600f8479.png)

**Comment by secret2base** [comment]
此工具基于谷歌浏览器，请确保电脑上已安装Chrome。

**Comment by drw2005** [comment]
> 此工具基于谷歌浏览器，请确保电脑上已安装Chrome。

我是64位WIN7，Chrome版本108.0.5359.125

**Comment by secret2base** [comment]
我是在win10环境下写和测试的，尚不清楚win7是否能运行，此问题的可能解决方案可尝试搜索selenium cannot find chrome binary。selenium库是最开始编写时使用的，1.0版本已部分移除selenium依赖，在后续我也计划使用requests完全取代selenium，到时候就不需要浏览器支持了。不清楚你使用此工具的目的，若确实需要，我会在新版本修改。
